// Environment detection constants
const ENVIRONMENT = {
  UNKNOWN: 'WEB',
  NWJS: 'NWJS',
  CORDOVA: 'CORDOVA',
  WEB: 'WEB'
};

// Build-time environment setting
const CURRENT_ENVIRONMENT = %;

const CORDOVA_EXTERNAL_DIRECTORY = "PadManiacs/";
const NWJS_EXTERNAL_DIRECTORY = "data/";

const EXTERNAL_DIRECTORY = CURRENT_ENVIRONMENT == ENVIRONMENT.CORDOVA ? CORDOVA_EXTERNAL_DIRECTORY : NWJS_EXTERNAL_DIRECTORY;

const ADDONS_DIRECTORY = "Addons";
const SCREENSHOTS_DIRECTORY = "Screenshots";
const SONGS_DIRECTORY = "Songs";

const ENABLE_PARALLEL_LOADING = true;
const MAX_PARALLEL_DOWNLOADS = 128;

const MAX_PARALLEL_ADDON_LOADS = 3;
const ENABLE_ADDON_SAFE_MODE = true;

const ENABLE_UI_SFX = false;
const ENABLE_EXP_SFX = true;

const REGULAR_VIBRATION_INTENSITY = 75;
const WEAK_VIBRATION_INTENSITY = 50;
const STRONG_VIBRATION_INTENSITY = 50;